version: "3.9"

services:
  backend:
    build: ./be
    container_name: django_backend
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./be:/app
      - media_volume:/app/media
      - static_volume:/app/static
    env_file:
      - ./be/.env
    expose:
      - "8000"
    depends_on:
      - db

  frontend:
    build:
      context: ./fe
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./fe:/app
      - /app/node_modules
    depends_on:
      - backend
    command: ["npm", "run", "build"]

  nginx:
    image: nginx:stable-alpine
    container_name: nginx_proxy
    ports:
      - "8200:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./fe/build:/usr/share/nginx/html
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - backend
      - frontend

  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: kioskdb
      POSTGRES_USER: rheavision
      POSTGRES_PASSWORD: 5145
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  media_volume:
  static_volume:
  pgdata: